### ISSUE TITLE
wasm branch yarn install failing

### ISSUE THREAD

**Issue by CodingItWrong** [Addepar/emberconf-schedule-2019#31]
I'm trying to build the `wasm` branch to get a sample of Glimmer with wasm running locally. I'm getting the following error:

```
error Fetch succeeded for undefined. However, extracting "./ember-source-3.2.0-master.tgz" resulted in hash "25d7e802a9636f87316d1fd3d0639fda9cef1083", which did not match the requested hash "2ccf1722b2774465a37a3cafdb4d926ccb8812e7
".
```

I tried doing a `yarn upgrade` to see if that helped, but then I started getting this error:

```
optionFeatures.isFeatureEnabled is not a function
```

I know this is just a branch of a one-time conference app, but if this is an easy fix, it would be cool to play with an app running wasm Glimmer locally! 😄

**Comment by kpfefferle** [comment]
I'm sorry that we didn't get this worked out for you. The WASM version was a last-minute addition to the project that really just proved that WASM was possible, and as you discovered it used a very specially compiled version of ember-source@3.2. At this time, we are likely not doing anything with WASM for the 2019 version, so I'm going to close this as something we are unlikely to address.
